import { Component } from '@angular/core';
import { OrderComponent } from "../../shared/components/order/order.component";

@Component({
    selector: 'app-orders',
    standalone: true,
    templateUrl: './orders.component.html',
    imports: [OrderComponent]
})


export class OrdersComponent {
    orders = [
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"1",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"2",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"3",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"4",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"5",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"6",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"7",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"8",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"9",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"10",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"11",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"12",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"13",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"14",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"15",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"16",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"17",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
        {preview: "https://cdn.britannica.com/61/93061-050-99147DCE/Statue-of-Liberty-Island-New-York-Bay.jpg",label:"18",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dignissim sapien quis aliquam pretium. Nunc vestibulum massa ornare lobortis tempor. Proin tincidunt blandit imperdiet. Suspendisse et condimentum tellus.",price:"19.99"},
    ]
}
